# --- CONEXÃO COM O POSTGRESQL ---
# Formato da URL: jdbc:postgresql://<HOST>:<PORTA>/<NOME_DO_BANCO>
spring.datasource.url=jdbc:postgresql://localhost:5432/Academia
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# --- CONFIGURAÇÕES DO JPA / HIBERNATE ---
# Define como o Hibernate deve gerenciar o esquema de tabelas:
# update: Atualiza a estrutura de tabelas existente sem apagar dados (recomendado para desenvolvimento)
# create-drop: Cria as tabelas ao iniciar e apaga tudo ao desligar a aplicação
# validate: Apenas valida se as entidades correspondem ao banco sem alterar nada (recomendado para produção)
spring.jpa.hibernate.ddl-auto=update

# Especifica o dialeto do PostgreSQL para o Hibernate gerar SQL otimizado
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mostra as queries SQL geradas no console da IDE
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.mvc.throw-exception-if-no-handler-found=true

server.error.include-stacktrace=always
server.error.include-message=always